# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='男', max_length=32),
        ),
    ]
